language: python
python:
  - "3.8"
install:
  - pip install -e .
#  - pip install -r requirements.txt
  - pip install pytest-cov codecov
script:
#  - pytest tests
  - pytest --cov=dsfun tests
after_success:
  - codecov
